import json
from typing import Protocol
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from backend.app.ai.models import AIMessage, AIResponse


class LLMGateway(Protocol):
    def generate(
        self,
        *,
        messages: list[AIMessage],
        prompt: str,
        context_payload: dict,
    ) -> AIResponse:
        ...


class DeterministicLLMGateway:
    """Provider-only deterministic gateway for local tests."""

    def generate(
        self,
        *,
        messages: list[AIMessage],
        prompt: str,
        context_payload: dict,
    ) -> AIResponse:
        hints = context_payload.get("responseHints", {})
        return AIResponse(
            answer=hints.get("answer", "Use the available context to choose the next action."),
            reasoning=hints.get("reasoning", "Generated from the provided context payload."),
            suggested_next_action=hints.get(
                "suggestedNextAction",
                "Review your current plan and continue the next task.",
            ),
            metadata=hints.get("metadata", {}),
        )


class OpenAICompatibleLLMGateway:
    """Server-only adapter for Chat Completions compatible model providers."""

    def __init__(self, *, base_url: str, api_key: str, model: str, timeout_seconds: int = 45) -> None:
        if not base_url or not api_key or not model:
            raise ValueError("AI_OPENAI_BASE_URL, AI_OPENAI_API_KEY, and AI_OPENAI_MODEL are required")
        self._endpoint = f"{base_url.rstrip('/')}/chat/completions"
        self._api_key = api_key
        self._model = model
        self._timeout_seconds = timeout_seconds

    def generate(
        self,
        *,
        messages: list[AIMessage],
        prompt: str,
        context_payload: dict,
    ) -> AIResponse:
        system_content = (
            f"{prompt}\n\n"
            "Use only the supplied context for claims about the learner's personal Knowledge. "
            "If no source is supplied, say that the explanation is general model knowledge.\n\n"
            f"Context:\n{json.dumps(context_payload, ensure_ascii=False, default=str)}"
        )
        body = json.dumps(
            {
                "model": self._model,
                "messages": [
                    {"role": "system", "content": system_content},
                    *[message.to_dict() for message in messages],
                ],
                "temperature": 0.2,
            }
        ).encode("utf-8")
        request = Request(
            self._endpoint,
            data=body,
            headers={
                "Authorization": f"Bearer {self._api_key}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with urlopen(request, timeout=self._timeout_seconds) as response:
                payload = json.loads(response.read().decode("utf-8"))
        except HTTPError as exc:
            raise RuntimeError(f"AI_PROVIDER_HTTP_{exc.code}") from exc
        except URLError as exc:
            raise RuntimeError("AI_PROVIDER_UNREACHABLE") from exc
        except TimeoutError as exc:
            raise RuntimeError("AI_PROVIDER_TIMEOUT") from exc
        try:
            content = payload["choices"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError) as exc:
            raise RuntimeError("AI_PROVIDER_INVALID_RESPONSE") from exc
        if isinstance(content, list):
            content = "".join(str(item.get("text", "")) for item in content if isinstance(item, dict))
        answer = str(content).strip()
        if not answer:
            raise RuntimeError("AI_PROVIDER_EMPTY_RESPONSE")
        return AIResponse(
            answer=answer,
            reasoning="Generated by the configured OpenAI-compatible AI Core provider.",
            suggested_next_action="Review the explanation, then decide whether to save it as your own learning note.",
            metadata={"model": self._model, "provider": "openai_compatible"},
        )
